-- Nettoyage
DROP TABLE IF EXISTS librairie.ex1_ventes CASCADE;
DROP TABLE IF EXISTS librairie.ex1_livres_genres CASCADE;
DROP TABLE IF EXISTS librairie.ex1_genres CASCADE;
DROP TABLE IF EXISTS librairie.ex1_livres CASCADE;
DROP TABLE IF EXISTS librairie.ex1_clients CASCADE;
DROP TABLE IF EXISTS librairie.ex1_auteurs CASCADE;


-- Création des tables

-- Auteurs
CREATE TABLE librairie.ex1_auteurs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL,
  pays TEXT
);

-- Clients
CREATE TABLE librairie.ex1_clients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL,
  email TEXT UNIQUE,
  pays TEXT
);

-- Livres
CREATE TABLE librairie.ex1_livres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre TEXT NOT NULL,
  prix NUMERIC(6,2) CHECK (prix >= 0),
  annee INT,
  auteur_id INT,
  CONSTRAINT fk_livre_auteur FOREIGN KEY (auteur_id) REFERENCES librairie.ex1_auteurs(id) ON DELETE SET NULL
);

-- Genres
CREATE TABLE librairie.ex1_genres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL UNIQUE
);

-- Table de liaison livres <-> genres
CREATE TABLE librairie.ex1_livres_genres (
  livre_id INT,
  genre_id INT,
  PRIMARY KEY (livre_id, genre_id),
  CONSTRAINT fk_lg_livre FOREIGN KEY (livre_id) REFERENCES librairie.ex1_livres(id) ON DELETE CASCADE,
  CONSTRAINT fk_lg_genre FOREIGN KEY (genre_id) REFERENCES librairie.ex1_genres(id) ON DELETE CASCADE
);

-- Ventes
CREATE TABLE librairie.ex1_ventes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  livre_id INT,
  client_id INT,
  qte INT CHECK (qte > 0),
  date_vente DATE NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT fk_vente_livre FOREIGN KEY (livre_id) REFERENCES librairie.ex1_livres(id) ON DELETE CASCADE,
  CONSTRAINT fk_vente_client FOREIGN KEY (client_id) REFERENCES librairie.ex1_clients(id) ON DELETE SET NULL
);

-- Insertion des données

-- Auteurs
INSERT INTO librairie.ex1_auteurs (nom, pays) VALUES
('Margaret Atwood','Canada'),
('Haruki Murakami','Japon'),
('Toni Morrison','USA');

-- Clients
INSERT INTO librairie.ex1_clients (nom, email, pays) VALUES
('Alice Dupont', 'alice@example.com', 'France'),
('Bob Smith', 'bob@example.com', 'USA'),
('Chihiro Tanaka', 'chihiro@example.jp', 'Japon');

-- Livres
INSERT INTO librairie.ex1_livres (titre, prix, annee, auteur_id) VALUES
('The Handmaid''s Tale', 19.99, 1985, 1),
('Oryx and Crake', 16.50, 2003, 1),
('Kafka on the Shore', 18.00, 2002, 2),
('Norwegian Wood', 15.00, 1987, 2),
('Beloved', 17.50, 1987, 3);

-- Genres
INSERT INTO librairie.ex1_genres (nom) VALUES
('Science-Fiction'),
('Dystopie'),
('Romance'),
('Littérature japonaise'),
('Historique');

-- Livres <-> Genres
INSERT INTO librairie.ex1_livres_genres (livre_id, genre_id) VALUES
(1, 2), -- The Handmaid's Tale -> Dystopie
(1, 1), -- The Handmaid's Tale -> Science-Fiction
(2, 1), -- Oryx and Crake -> Science-Fiction
(3, 4), -- Kafka on the Shore -> Littérature japonaise
(4, 3), -- Norwegian Wood -> Romance
(4, 4), -- Norwegian Wood -> Littérature japonaise
(5, 5); -- Beloved -> Historique

-- Ventes
INSERT INTO librairie.ex1_ventes (livre_id, client_id, qte, date_vente) VALUES
(1, 1, 3, '2025-09-01'),
(2, 2, 1, '2025-09-02'),
(3, 3, 4, '2025-09-02'),
(4, 3, 2, '2025-09-03'),
(5, 2, 5, '2025-09-03');